pipeline {
	agent any  // run on any agent including master

	// To select the agent, use the below block
	// agent {
	// 	label "Master"
	// }

	tools {  // Names of the tools should be same as added in jenkins tools configuration
	    maven "MAVEN3.9"	// maven is the tool and MAVEN3.9 is the name added in tool configuration
	    jdk "JDK17"
	}

	stages {
	    stage('Fetch code') {
            steps {
               git branch: 'atom', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }

	    }


       stage('UNIT TEST') {
            steps{
                sh 'mvn test'
            }
        }


	    stage('Build'){
	        steps{
	           sh 'mvn install -DskipTests'
	        }

	        post {
	           success {
	              echo 'Now Archiving it...'
	              archiveArtifacts artifacts: '**/target/*.war'
	           }
	        }
	    }

	    
	}
}